name: run main.py

on:
  push:     # Trigger workflow on a push to the 'main' branch
    branches:
      - main

  # schedule: # Trigger workflow at 1 Jan 00h00 (https://crontab.guru)
  #  - cron: '*/15 * * * *' 

permissions:
  id-token: write  # Required for Workload Identity Federation
  contents: read   # To read repository content (checkout action)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: google workload identity provider
        uses: google-github-actions/auth@v2
        with:
          project_id: 'haoshoken'
          workload_identity_provider: 'projects/289880474417/locations/global/workloadIdentityPools/github/providers/dailypy'
          service_account: 'gsheet-accessor@haoshoken.iam.gserviceaccount.com'

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install gspread google-auth
          pip install -r requirements.txt

      - name: execute py script # run main.py
        env:
          SOME_SECRET: ${{ secrets.SOME_SECRET }}
          GOOGLE_APPLICATION_KEY: ${{ secrets.GOOGLE_APPLICATION_KEY }}

        run: python main.py        
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main